version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
  ghpr: narrativescience/ghpr@1.1.2
  slack: circleci/slack@4.5
  cypress: cypress-io/cypress@1.29.0

target-preprod-smokes: &target-preprod-smokes
  domain: preprod-veygo.com
  context:
    - github
    - smoke-test
    - slack

commands:
  alert-failed-build:
    steps:
      - run: exit 0
      - slack/notify:
          event: fail
          channel: salesforce-integration
          mentions: '@here'
          template: JOB_FAILURE_TEMPLATE
          branch_pattern: master
  run-smoke-tests:
    parameters:
      path:
        type: string
      product:
        type: string
      subdomain:
        type: enum
        default: 'quote'
        enum: ['quote', 'account', 'login']
      domain:
        type: string
    steps:
      - run:
          name: Clone Monorepo
          command: |
            cd ..
            git clone git@github.com:Rentecarlo/csi.git
      - cypress/install:
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "<< parameters.path >>/cypress/yarn.lock" }}'
          yarn: true
          working_directory: << parameters.path >>/cypress
          no-workspace: true
      - run:
          name: Run Cypress tests
          command: |
            CYPRESS_baseUrl=https://<< parameters.subdomain >>.<< parameters.domain >> yarn cypress:run --env failfast=true --reporter junit --reporter-options mochaFile=../results/smoke/<< parameters.product >>/result.[hash].xml --spec "tests/smoke/<< parameters.product >>/**"
          working_directory: << parameters.path >>/cypress
      - store_test_results:
          path: << parameters.path >>/results/smoke
      - store_artifacts:
          path: << parameters.path >>/results/smoke
      - store_artifacts:
          path: << parameters.path >>/cypress/videos
      - store_artifacts:
          path: << parameters.path >>/cypress/screenshots
      - alert-failed-build

jobs:
  validate-pr-title:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run:
          name: Skip if no PR linked
          command: |
            if [[ -z $CIRCLE_PULL_REQUEST ]]; then
              circleci step halt
            fi
      - ghpr/get-pr-info
      - run:
          name: Validate PR Title
          command: |
            echo "GITHUB_PR_TITLE: $GITHUB_PR_TITLE"
            PR_TITLE_REGEX='^\([A-Z]{3} AB#[0-9]{1,5}\) .*'
            [[ $GITHUB_PR_TITLE =~ $PR_TITLE_REGEX ]] && echo "PR title is valid" && exit 0
            exit 1
  validate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: $SALESFORCE_USERNAME
          instanceUrl: https://test.salesforce.com
      - run:
          name: Validate
          command: sfdx force:source:deploy --checkonly --sourcepath veygo-app --targetusername $SALESFORCE_USERNAME --testlevel RunLocalTests
  deploy:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: $SALESFORCE_USERNAME
          instanceUrl: https://test.salesforce.com
      - run:
          name: Deploy
          command: sfdx force:source:deploy --sourcepath veygo-app --targetusername $SALESFORCE_USERNAME --testlevel RunLocalTests
      - slack/notify:
          event: fail
          channel: salesforce-integration
          mentions: '@here'
          template: JOB_FAILURE_TEMPLATE
          branch_pattern: master
  post-release-notes:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Get PR Title
          command: |
            GITHUB_LAST_COMMIT_INFO=$(git show $CIRCLE_SHA1)
            GITHUB_PR_TITLE_DIRTY=${GITHUB_LAST_COMMIT_INFO##*$'\n'}
            read GITHUB_PR_TITLE \<<< $( echo ${GITHUB_PR_TITLE_DIRTY} | awk -F"|" '{ sub(/^[ \t]+/, ""); print }' )
            echo "GITHUB_PR_TITLE: $GITHUB_PR_TITLE"
            echo "export GITHUB_PR_TITLE='$GITHUB_PR_TITLE'" >> $BASH_ENV
      - run:
          name: Set Azure Boards URL
          command: |
            TMP_STRING=${GITHUB_PR_TITLE%%)*}
            AZURE_BOARDS_ID=${TMP_STRING:8}
            AZURE_BOARDS_URL="https://dev.azure.com/Veygo/Veygo/_workitems/edit/${AZURE_BOARDS_ID}"
            echo "AZURE_BOARDS_URL: $AZURE_BOARDS_URL"
            echo "export AZURE_BOARDS_URL='$AZURE_BOARDS_URL'" >> $BASH_ENV
      - slack/notify:
          event: pass
          channel: salesforce-integration
          template: SUCCESSFUL_DEPLOYMENT_TEMPLATE
  dtc-smoke:
    circleci_ip_ranges: true
    docker:
      - image: cypress/base:14
    resource_class: medium
    parameters:
      domain:
        type: string
    steps:
      - checkout
      - run-smoke-tests:
          path: ~/csi/frontends/packages/new-frontend
          product: driverTempCover
          subdomain: quote
          domain: << parameters.domain >>
  account-smoke:
    circleci_ip_ranges: true
    docker:
      - image: cypress/base:14
    resource_class: medium
    parameters:
      domain:
        type: string
    steps:
      - checkout
      - run-smoke-tests:
          path:  ~/csi/frontends/packages/account
          product: account
          subdomain: account
          domain: << parameters.domain >>
  auth-smoke:
    circleci_ip_ranges: true
    docker:
      - image: cypress/base:14
    resource_class: medium
    parameters:
      domain:
        type: string
    steps:
      - checkout
      - run-smoke-tests:
          path: ~/csi/frontends/packages/auth-frontend
          product: login
          subdomain: login
          domain: << parameters.domain >>

workflows:
  main:
    jobs:
      - validate-pr-title:
          context:
            - github
          filters:
            branches:
              ignore:
                - master
      - validate:
          context:
            - SALESFORCE_DEV
          filters:
            branches:
              ignore:
                - master
      - deploy:
          name: deploy-dev
          context:
            - SALESFORCE_DEV
            - slack
          filters:
            branches:
              only:
                - master
      - deploy:
          name: deploy-qa
          context:
            - SALESFORCE_QA
            - slack
          requires:
            - deploy-dev
      - dtc-smoke:
          requires:
            - deploy-qa
          <<: *target-preprod-smokes
      - account-smoke:
          requires:
            - deploy-qa
          <<: *target-preprod-smokes
      - auth-smoke:
          requires:
            - deploy-qa
          <<: *target-preprod-smokes
      - post-release-notes:
          context:
            - slack
          requires:
            - dtc-smoke
            - account-smoke
            - auth-smoke
