/**
 * @description       : 
 * @author            : matteo.iacucci@emea.merkleinc.com
 * @group             : 
 * @last modified on  : 2021-08-04
 * @last modified by  : matteo.iacucci@emea.merkleinc.com
**/
public with sharing class Constants {
    public static final String QUOTE_STARTED = 'QUOTE_STARTED';
    public static final String QUOTE_UPDATED = 'QUOTE_UPDATED';
    public static final String QUOTE_SALECOMPLETED = 'SALE_COMPLETED';

    public static final String CONVERTED_LEADSTATUS = 'Qualified';

    public static final String CLOSE_OPPORTUNITY = 'Closed Won';
}
