/**
 * @description       : 
 * @author            : matteo.iacucci@emea.merkleinc.com
 * @group             : 
 * @last modified on  : 2021-08-10
 * @last modified by  : matteo.iacucci@emea.merkleinc.com
**/
public with sharing class Constants {
    public static final String QUOTE_STARTED = 'QUOTE_STARTED';
    public static final String QUOTE_UPDATED = 'QUOTE_UPDATED';
    public static final String QUOTE_SALECOMPLETED = 'SALE_COMPLETED';

    public static final String POLICY_UPDATED = 'POLICY_UPDATED';
    public static final String POLICY_CANCELED = 'POLICY_CANCELLED';

    public static final String LEAD_QUOTESTART = 'QUOTE_STARTED';
    public static final String LEAD_INDICATIVEQUOTE = 'Indicative Quote';
    public static final String LEAD_FULLQUOTE = 'Full Quote';
    public static final String CONVERTED_LEADSTATUS = 'Qualified';

    public static final String OPPORTUNITY_QUOTESTART = 'Quote Start';
    public static final String OPPORTUNITY_INDICATIVEQUOTE = 'Indicative Quote';
    public static final String OPPORTUNITY_FULLQUOTE = 'Full Quote';
    public static final String OPPORTUNITY_CLOSED = 'Closed Won';   
}
